"""template title

Revision ID: 75fa56a7a0d3
Revises: b26d9b94bc85
Create Date: 2023-09-14 21:14:04.970391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75fa56a7a0d3'
down_revision = 'b26d9b94bc85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template', sa.Column('title', sa.String(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template', 'title')
    # ### end Alembic commands ###
