"""add templates

Revision ID: b26d9b94bc85
Revises: 6488deec84c6
Create Date: 2023-09-12 19:31:01.381135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b26d9b94bc85'
down_revision = '6488deec84c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('answer', sa.Column('template_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'answer', 'template', ['template_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.drop_column('answer', 'template_id')
    op.drop_table('template')
    # ### end Alembic commands ###
